version: '1.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: gem_nextjs_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules