const prefixPath = `/images/`;

export const imgSrc = {
  boyLoginImg: `/images/login_image_boy.png`,
  girlLoginImg: `/images/login_image_girl.png`,
  ppclinkLogo: `/images/ppclink_logo.png`,
  lichVietLogo: `/images/logo_lichviet.png`,
  conSoBackground: `/images/con_so_background.png`,
  giaiDoanCuocDoi: `/images/giai_doan_cuoc_doi.png`,
  conSoChuDaoBackground: `/images/con_so_chu_dao_background.png`,
  cacConSoKhacBackground: `/images/cac_con_so_khac_background.png`,
  checkBoxGreen: `/images/checkbox_green.jpg`,
  bannerTaiAppNhanQua2: `/images/banner_tai_app_nhan_qua2.jpg`,
  iconDongHo: `/images/icon_dong_ho.jpg`,
  bgHdKbank: `/images/bg_hd_kbank.jpg`,
  buttonDangKyNgay: `/images/button_dang_ky_ngay.png`,
  iconDownload: `/images/icon_download.png`,
  iconNotebook: `/images/icon_notebook.png`,
  iconPlay: `/images/icon_play.png`,
  backgroundFooterKbank: `/images/background_footer_kbank.png`,
  lichVietQr: `/images/lich_viet_qr.png`,
  muaLichVietProBanner: `/images/mua_lich_viet_pro_banner.png`,
  nangCapChonNgayTot: `/images/nang_cap_chon_ngay_tot.png`,
  nangCapGiaiMaNgaySinh: `/images/nang_cap_giai_ma_ngay_sinh.png`,
  nangCapGieoQueHoiViec: `/images/nang_cap_gieo_que_hoi_viec.png`,
  nangCapTronBoLichViet: `/images/nang_cap_tron_bo_lich_viet.png`,
  nangCapXemNgayTotChuyenGia: `/images/nang_cap_xem_ngay_tot_chuyen_gia.png`,
  nangCapXemPhongThuy: `/images/nang_cap_xem_phong_thuy.png`,
  nangCapXemTuVi: `/images/nang_cap_xem_tu_vi.png`,
  nangCapXemTuViChuyenGia: `/images/nang_cap_xem_tu_vi_chuyen_gia.png`,
  contactLichVietProBoyBackground: `/images/contact_lich_viet_pro_boy_background.png`,
  contactLichVietProGirlBackground: `/images/contact_lich_viet_pro_girl_background.png`,
  chonNgayTotBanner1: `/images/chon_ngay_tot_banner_1.png`,
  chonNgayTotBanner2: `/images/chon_ngay_tot_banner_2.png`,
  chonNgayTotBanner3: `/images/chon_ngay_tot_banner_3.png`,
  chonNgayTotBanner4: `/images/chon_ngay_tot_banner_4.png`,
  chonNgayTotBanner5: `/images/chon_ngay_tot_banner_5.png`,
  chonNgayTotBanner6: `/images/chon_ngay_tot_banner_6.png`,
  chonNgayTotBanner7: `/images/chon_ngay_tot_banner_7.png`,
  chonNgayTotVideoTitle: `/images/chon_ngay_tot_video_title.png`,
  imgChuyenGia: `/images/img_chuyen_gia.png`,
  quyTrinhChamSocKhachHang: `/images/quy_trinh_cham_soc_khach_hang.png`,
  iconPhone: `/images/icon_phone.png`,
  iconZalo: `/images/icon_zalo.png`,
  imgUuDaiContactChuyenGia: `/images/img_uu_dai_contact_chuyen_gia.png`,
  imgGoiBaThang: `/images/img_goi_3_thang.png`,
  imgGoiSauThang: `/images/img_goi_6_thang.png`,
  imgGoiMotNam: `/images/img_goi_1_nam.png`,

};
