export const imgSrc = {
  boyLoginImg: "/images/login_image_boy.png",
  girlLoginImg: "/images/login_image_girl.png",
  ppclinkLogo: "/images/ppclink_logo.png",
  lichVietLogo: "/images/logo_lichviet.png",
  conSoBackground: "/images/con_so_background.png",
  giaiDoanCuocDoi: "/images/giai_doan_cuoc_doi.png",
  conSoChuDaoBackground: "/images/con_so_chu_dao_background.png",
  cacConSoKhacBackground: "/images/cac_con_so_khac_background.png",
  checkBoxGreen: "/images/checkbox_green.jpg",
  bannerTaiAppNhanQua2: "/images/banner_tai_app_nhan_qua2.jpg",
  iconDongHo: "/images/icon_dong_ho.jpg",
  bgHdKbank: "/images/bg_hd_kbank.jpg",
  buttonDangKyNgay: "/images/button_dang_ky_ngay.png",
  iconDownload: "/images/icon_download.png",
  iconNotebook: "/images/icon_notebook.png",
  iconPlay: "/images/icon_play.png",
  backgroundFooterKbank: "/images/background_footer_kbank.png",
  lichVietQr: "/images/lich_viet_qr.png",
};
